[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.62"
clap = { version = "4.0.29", features = ["derive", "env"] }
prost = "0.11.3"
serde = { version = "1.0.143", features = ["derive", "rc"] }
tokio = { version = "1.23.0", features = ["full"] }
tokio-stream = { version = "0.1.9", features = ["sync"] }
tonic = { version = "0.9.2", features = ["tls", "tls-roots"] }
tracing = "0.1.30"
tracing-subscriber = "0.3.8"

[profile.release]
strip = true
