[package]
name = "sshx-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-channel = "1.6.1"
async-stream = "0.3.3"
axum = { version = "0.6.0", features = ["ws"] }
base64 = "0.21.0"
bytes = { version = "1.5.0", features = ["serde"] }
ciborium = "0.2.0"
clap.workspace = true
dashmap = "5.2.0"
hmac = "0.12.1"
hyper = { version = "0.14.18", features = ["full"] }
parking_lot = "0.12.0"
rand.workspace = true
serde.workspace = true
sha2 = "0.10.2"
sshx-core = { path = "../sshx-core" }
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tonic-reflection = "0.9.2"
tower = { version = "0.4.12", features = ["steer"] }
tower-http = { version = "0.4.1", features = ["fs", "redirect", "trace"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
futures-util = { version = "0.3.23", features = ["sink"] }
reqwest = "0.11.10"
sshx = { path = "../sshx" }
tokio-tungstenite = "0.18.0"
